### ISSUE TITLE
Create Vagrant file for orders microservice virtual machine

### ISSUE THREAD

**Issue by mstefaniak10** [devopsorders/orders#1]
**As a** Developer
**I need** a way to work locally
**So that** I can be independent of any cloud environment 

**Assumptions:** 
* Use Vagrant and VirtualBox to build a local environment
* Python (ideally python3) will be used for development

**Acceptance Criteria:**

When I issue `git clone` on the project
Add I change into the project folder
And I issue `vagrant up`
Then I should have a complete development environment on my workstation

**Comment by shooker** [comment]
Make sure to exclude .vagrant folders in .gitignore file

**Comment by mstefaniak10** [comment]
Should have a docker container running Postgres so we can store orders

**Comment by shooker** [comment]
Run `vagrant up` and visit 192.168.33.10 in a browser to confirm Apache is running.
