### ISSUE TITLE
Add QUERY functionality for orders

### ISSUE THREAD

**Issue by jr4998** [devopsorders/orders#11]
**As a** User
**I need** to be able to search through my previous orders 
**So that** I can locate specific orders

**Assumptions:** 
* users can view orders in chronological order 
* users can view orders placed only in the last 6 months by default
* users can search based on order number, date

**Acceptance Criteria:**

When I call GET /orders?
Then I receive a json with the details of the specific order I am searching

Test case will be written before development

**Comment by shooker** [comment]
For now, this ticket is simply going to query by status. We will open an additional ticket if querying by date is required.
