### ISSUE TITLE
Create a skeleton Flask project to seed repo

### ISSUE THREAD

**Issue by mstefaniak10** [devopsorders/orders#2]
**As a** Developer 
**I need** some starter code 
**So that** I can start adding features

**Assumptions:** 
* We will be using Python with Flask
* Just the bare bones app for now

**Acceptance Criteria:**

When I issue a `git clone` on the project
I should get a minimal Flask application
When I run `python app.py`
I should have a Flask server running at `localhost:5000`

**Comment by ShreeyaShekar** [comment]
make sure to include models.py, service.py files

**Comment by mstefaniak10** [comment]
This should also include a requirements.txt file
