### ISSUE TITLE
Full featured RESTful orders api with persistence

### ISSUE THREAD

**Issue by mstefaniak10** [devopsorders/orders#3]
**As a** ...  
**I need** ...  
**So that** ...  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by shooker** [comment]
The API should only return JSON including error messages from the web server, we must override the default error handlers.

**Comment by shooker** [comment]
Ensure full logging is available for debugging.
