### ISSUE TITLE
Get Database credentials from an environment variable 

### ISSUE THREAD

**Issue by jr4998** [devopsorders/orders#40]
**As a** developer
**I need** to keep the database connection info out of the codebase
**So that** my application is secure and easy to modify in the future

**Assumptions:** 
* create a PostgreSQL from ElephantSQL.com

**Acceptance Criteria:**

Given I start my web app  
When I make a GET request
Then the app successfully connects to the database using an environment variable

**Comment by mstefaniak10** [comment]
Make sure to see the readme, where you have to copy .sample-env to .env to run locally. Ask me privately for postgres connection credentials
