### ISSUE TITLE
Download and install the IBM Cloud CLI in my vagrant VM

### ISSUE THREAD

**Issue by ShreeyaShekar** [devopsorders/orders#46]
**As a** Developer
**I need** to download and install the IBM Cloud CLI in my vagrant VM
**So that** I can run vagrant up successfully with the IBM Cloud CLI tools installed

**Assumptions:** 
* I use my API key to push to a shared account

**Acceptance Criteria:**

When I run vagrant ssh and type `cf version`
Then it runs successfully with the IBM Cloud CLI tools installed

**Comment by shooker** [comment]
I have "bx" commands working, but for "cf" commands to run, I need to [install CloudFoundry](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html), which is technically different than the IBM Cloud CLI. I followed the [demo](https://github.com/nyu-devops/lab-bluemix-cf/blob/master/Vagrantfile), should I make a new ticket for CloudFoundry? I don't see it in the homework requirements, so I'm thinking we just need Bluemix. We can chat at our standup.

**Comment by shooker** [comment]
FYI when this is pushed you may need to run `vagrant provision`
