### ISSUE TITLE
Create Automated Script to Run Code Through Linter 

### ISSUE THREAD

**Issue by shooker** [devopsorders/orders#5]
**As a** Developer
**I need** my code to automatically run through PyLint
**So that** my code conforms to the PEP8 Python standard

**Assumptions:** 
* When automated tests are deployed, this is included as a part of the test suite

**Acceptance Criteria:**
```
Given code checked in
When the automated tests are run
Then I can see a report of my code quality
```

**Comment by mstefaniak10** [comment]
You can now run pylint on individual files, ex. pylint app.py .   Will hold on automation until we get to using a continuous integration server

**Comment by shooker** [comment]
Should we open a separate issue to address the automation after we close this issue/merge it in?

**Comment by mstefaniak10** [comment]
Ya separate issue
