### ISSUE TITLE
Allow All Developers to Deploy to Shared CloudFoundry Organization

### ISSUE THREAD

**Issue by shooker** [devopsorders/orders#56]
**As a** Developer
**I need** access to the shared CloudFoundry organization
**So that** I can deploy the latest version of the codebase

**Assumptions:** 
* The organization is under @shooker account called sebastian.hooker@stern.nyu.edu
* Only the `master` branch will be deployed to the cloud
* IBM Trial accounts allow multiple CloudFoundry organizations

**Acceptance Criteria:**

When I run the `ibmcloud login` command and list organizations from an account that does not belong to @shooker 
Then login completes successfully, lists sebastian.hooker@stern.nyu.edu as an organization, and I can use the `cf push` command to deploy code

**Comment by mstefaniak10** [comment]
Everything seems set up correctly, when I run `bx cf orgs` I see Sebastian's organization, but when I try to login using that organization, it returns with that organization not found under my account

**Comment by mstefaniak10** [comment]
We are 95% sure this doesn't work correctly due to limitations with Lite accounts

**Comment by mstefaniak10** [comment]
Closing as work has been attempted on this ticket. Will open a new ticket to track ongoing progress on this issue
